### ISSUE TITLE
Epic - Standardize CoP name across org as DevOps

### ISSUE THREAD

**Issue by chelseybeck** [hackforla/ops#108]
### Dependency
- [ ] #156
- [ ] #155 
- [ ] #157
- [ ] [Website issue 8286](https://github.com/hackforla/website/issues/8286) 

### Overview

Currently, the DevOps Community of Practice (CoP) is referred to by both DevOps and Ops in a lot of documentation (code repo, website, and Google drive). We need to make it DevOps across the org.

**Comment by freaky4wrld** [comment]
Here's a checklist of instances with `Ops/ops` that's going to be changes to `DevOps` :
- [x] [DevOps Readme.md](https://github.com/hackforla/ops/blob/c15c6c96290ab0fb5069b1cd7d805a3a643b77a7/README.md?plain=1)
- [x] [DevOps 2020 agenda](https://github.com/hackforla/ops/blob/c15c6c96290ab0fb5069b1cd7d805a3a643b77a7/2020-agendas/2020-12-15.md?plain=1#L2)  **maybe we can ignore this, or make changes if we are using it for recording history**
- [x] [Issue Template onboard-ops-cop-lead.md](https://github.com/hackforla/ops/blob/c15c6c96290ab0fb5069b1cd7d805a3a643b77a7/.github/ISSUE_TEMPLATE/onboard-ops-cop-lead.md?plain=1#L2)
- [x] [Issue Template offboard-ops-cop-lead.md](https://github.com/hackforla/ops/blob/c15c6c96290ab0fb5069b1cd7d805a3a643b77a7/.github/ISSUE_TEMPLATE/offboard-ops-cop-lead.md?plain=1#L2)
- [x] [ssue Template recruit-new-lead.md](https://github.com/hackforla/ops/blob/c15c6c96290ab0fb5069b1cd7d805a3a643b77a7/.github/ISSUE_TEMPLATE/recruit-new-lead.md?plain=1#L4)
- [x] [@danielridgebot ops wiki](https://github.com/hackforla/ops/wiki/%40danielridgebot-Ops-Wiki)
- [x] [Community Leads Roles wiki](https://github.com/hackforla/ops/wiki/Community-Leads-Roles)
- [x] [Home wiki](https://github.com/hackforla/ops/wiki)
- [x] [Community wiki](https://github.com/hackforla/ops/wiki/Community)
- [x] [CoP Meetings wiki](https://github.com/hackforla/ops/wiki/CoP-Meetings)
- [x] [AWS User Management wiki](https://github.com/hackforla/ops/wiki/AWS-User-Management)

            - just noticed a spelling error `utulized` at `bullet point number 8 Note`
            
- [x] [CoP Page](https://www.hackforla.org/communities-of-practice)

             - the title can be changed to DevOps
             - the introductory line `This group covers all areas of dev-ops` can be changed to `This group covers all areas of DevOps`
            
- [x] [DevOps Drive link](https://drive.google.com/drive/folders/1XBuLSjOEKGfeVvWluIDyPYXTKHXhYHDM?usp=sharing)

**Comment by freaky4wrld** [comment]
@chelseybeck as the requirement, provided the links to where the changes are to be made....... just a suggestion we should use `spellchecker-extension` to avoid `spelling-errors`......... please review the links in the comment and suggest changes, thanks

**Comment by chelseyklein** [comment]
This is great, @freaky4wrld. Thank you! I think one more place to look is the Google Drive. We may need to change the drive name, etc.

**Comment by ExperimentsInHonesty** [comment]
We need to create new issues from this list to have two different PRs.  One that can be merged that just changes working and another that changes links.  The wording one, we can merge anytime, the one that changes any links to repos, will need to be held and merged directly after the URL has been change.

**Comment by ExperimentsInHonesty** [comment]
@freaky4wrld Should we unassign you from this before we decompose it?

**Comment by ExperimentsInHonesty** [comment]
There are more places to check.  The issue needs to be rewritten

**Comment by ale210** [comment]
consider adding a spreadsheet to track this instead of the issue

Columns:
Location
Url that needs to be changed
Type: Text/Link
Inbound links: checkbox (true/false)
