### ISSUE TITLE
Create a deployment checklist for deploying a project into production infrastructure

### ISSUE THREAD

**Issue by sudhara** [hackforla/ops#145]
### Dependency
- https://github.com/hackforla/incubator/issues/20

### Overview

As a developer, we need a checklist for deploying a project into production infrastructure so that it's easy for the project team to plan, prepare and deploy applications into production.

### Action Items

- [ ] Pre-Deployment checklist
- [ ] Deployment Checklist
- [ ] Post-deployment checklist

### Resources/Instructions
- [Resources](https://github.com/hackforla/ops/wiki)

**Comment by Aditya23soni** [comment]
<details><summary>Prior version of issue</summary>
<p>

### Dependency

TBD

### Overview

As a developer, we need a checklist for deploying a project into production infrastructure so that it's easy for the project team to plan, prepare and deploy applications into production.

### Action Items

- [ ] Pre-Deployment checklist
- [ ] Deployment Checklist
- [ ] Post-deployment checklist


### Resources/Instructions

[Resources](https://github.com/hackforla/ops/wiki)
</p>
</details>

**Comment by Aditya23soni** [comment]
<details><summary>Assignee, Labels, Project Board Placement, and Milestones for this issue in the Ops Repo:</summary>
<p>
<img width="337" alt="Screenshot 2024-10-04 at 4 23 47 PM" src="https://github.com/user-attachments/assets/0405fb7f-a5db-4c07-900b-b383ede35b26">
</p>
</details>

**Comment by Aditya23soni** [comment]
@sudhara This guide issue is moving to the knowledgebase-content repo. If you would like to maintain edit access to the issue and its associated files, please fill out the [Google Drive Access Form](https://forms.gle/vnKRqprNYJUG5ET69)

**Comment by ale210** [comment]
this is a duplicate of [#50](https://github.com/hackforla/incubator/issues/50)
