### ISSUE TITLE
Create Ops Roadmap

### ISSUE THREAD

**Issue by JasonEb** [hackforla/ops#24]
### Overview

We need to create a roadmap using milestone in order to prioritize the work for team members.

### Action Items
- [x] Read into Milestones documentation
- [x] List existing milestones in a comment
- [ ] Do a road mapping session
   - [ ] Decide if some milestones need to exist on all repos
   - [ ] How to prioritize if all repositories don't use the same milestones/numbering schema?

### Resources/Instructions

- https://github.com/hackforla/product-management/wiki/Milestones
- [Ops: Roadmap spreadsheet](https://docs.google.com/spreadsheets/d/1BbeyeM45FnN3mBqen2mFMYfcUGJdxrhhQ0USu46gYu8/edit#gid=2140061635)
- [Ops Repo milestones](https://github.com/hackforla/ops/milestones?direction=asc&sort=title&state=open)
- [DevOps Security milestones](https://github.com/hackforla/devops-security/milestones)
- [Incubator milestones](https://github.com/hackforla/incubator/milestones?direction=asc&sort=title&state=open)
- [ghpages - docker - no milestones](https://github.com/hackforla/ghpages-docker)
- [check ghpages-versions no milestones](https://github.com/danielridgebot/check-ghpages-versions/milestones)

**Comment by ale210** [comment]
very basic roadmap is at:
https://github.com/hackforla/ops/wiki/DevOps-Roadmap
