### ISSUE TITLE
Create a Guide/Template: How to Troubleshoot Using 1Password's One-time Password and How to Use Backup Codes

### ISSUE THREAD

**Issue by JessicaLucindaCheng** [hackforla/ops#41]
### Overview
We need to create a guide to setting up one-time passwords in 1Password for use with 2FA in GitHub accounts so that all login information is located within 1Password.

### Action Items
- [ ] Add the "TG: Create Guide" label
- [ ] Create a guide 
   - [ ] Once done, remove the "TG: Create Guide" label and add the "TG: Review Guide" label
- [ ] Review the guide with product management communities of practice
   - [ ] Once done, remove the "TG: Review Guide" label and add the "TG: Leadership Review" label
- [ ] Present to Hack for LA leadership team for sign off
   - [ ] Once approved, remove the "TG: Leadership Review" label and add the "TG: Place Guide" label
- [ ] Possibly create an issue template on .github 
   - [ ] Include link to template under resources if you add it as a template in .github

### Resources
Update tracker issue (TBD) with the name of item you are working
- Directory in Google Drive:

**Comment by JessicaLucindaCheng** [comment]
@JasonEb Thanks for reaching out. I am so sorry I missed your comment in this issue earlier. Could you please @mention me in the future? Since I get so many notifications, the @mention helps me filter my notifications and prioritize ones that are directed directly towards me.

**Comment by JessicaLucindaCheng** [comment]
- Progress: None but worked on a similar guide for Google Accounts: [Guide: How to Set Up 2-Step Verification in a Google Account Using 1Password](https://docs.google.com/document/d/1qFs_ceyA4PtnLBIZQPONvmgKovWXOi2hkbDBJybgn7A/edit?usp=sharing), which will help with the writing of this guide. I'm taking a few weeks week off from Hack for LA, except for attending a few meetings, responding to Slack messages, and dealing with GitHub notifications. I should be back fully by Thursday, September 15, 2022.
- Blockers: None
- Availability: None until Thursday, September 15, 2022
- ETA: Not sure yet.

**Comment by JasonEb** [comment]
Hey Jessica, lets provide an update
1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures or links* (if necessary): "Add any pictures or links that will help illustrate what you are working on."

* remember to add links to the top of the issue if they are going to be needed again.

**Comment by JessicaLucindaCheng** [comment]
Progress: I plan on starting to write up the guide including images this week hopefully; if not, then next week. None but worked on a similar guide for Google Accounts: [Guide: How to Set Up 2-Step Verification in a Google Account Using 1Password](https://docs.google.com/document/d/1qFs_ceyA4PtnLBIZQPONvmgKovWXOi2hkbDBJybgn7A/edit?usp=sharing), which will help with the writing of this guide.
Blockers: None
Availability: 6 hours this week
ETA: November 14, 2022

**Comment by JessicaLucindaCheng** [comment]
Progress: I plan on starting to write up the guide including images this week. None but worked on a similar guide for Google Accounts: [Guide: How to Set Up 2-Step Verification in a Google Account Using 1Password](https://docs.google.com/document/d/1qFs_ceyA4PtnLBIZQPONvmgKovWXOi2hkbDBJybgn7A/edit?usp=sharing), which will help with the writing of this guide.
Blockers: None
Availability: 6 hours this week
ETA: November 14, 2022

**Comment by JessicaLucindaCheng** [comment]
Progress: None because I have been having Internet issue. However, I worked on a similar guide for Google Accounts: [Guide: How to Set Up 2-Step Verification in a Google Account Using 1Password](https://docs.google.com/document/d/1qFs_ceyA4PtnLBIZQPONvmgKovWXOi2hkbDBJybgn7A/edit?usp=sharing), which will help with the writing of this guide.
Blockers: None
Availability: Not sure this week
ETA: November 30, 2022 for first draft

**Comment by JessicaLucindaCheng** [comment]
### Progress update
- Progress: Internet has been fixed
- Blockers: None
- Availability: Not sure this week
- ETA: Jaunary 10, 2022 for first draft

### Notes
- [Guide: How to Set Up 2-Step Verification in a Google Account Using 1Password](https://docs.google.com/document/d/1qFs_ceyA4PtnLBIZQPONvmgKovWXOi2hkbDBJybgn7A/edit?usp=sharing), which will help with the writing of this guide.

**Comment by JessicaLucindaCheng** [comment]
- Progress: I started a rough draft
- Blockers: None yet
- Availability: 6 hours
- ETA: Thu, Dec 23, 2022

**Comment by JessicaLucindaCheng** [comment]
**Progress update**
- Progress: I started a rough draft
- Blockers: None yet
- Availability: 6 hours
- ETA: Sun, Jan 1, 2023 for first draft

**Tasks**
- [ ] When the guide for this issue is done, in [_Guide: Log into a Google Account with 2-Step Verification Using 1Password_ ](https://docs.google.com/document/d/1hL3gYqoV6EWl4bUa2VYLgq0N__CjTvSw4Da2M4x2Hxk/edit#), replace the troubleshoot section with a link to this guide.

**Comment by JessicaLucindaCheng** [comment]
**Progress update**
- Progress: I started a first draft but didn't quite finish it
- Blockers: None yet
- Availability: 6 hours
- ETA: Thu, Jan 12, 2023 to complete first draft

**Tasks**
- [ ] When the guide for this issue is done, in [_Guide: Log into a Google Account with 2-Step Verification Using 1Password_](https://docs.google.com/document/d/1hL3gYqoV6EWl4bUa2VYLgq0N__CjTvSw4Da2M4x2Hxk/edit#), replace the troubleshoot section with a link to the troubleshooting guide.

**Comment by JessicaLucindaCheng** [comment]
**Progress update**
- Progress: I started a first draft but didn't quite finish it
- Blockers: None yet
- Availability: 6 hours
- ETA: Tue, Jan 24, 2023 to complete first draft

**Tasks**
- [ ] When the guide for this issue is done, in [_Guide: Log into a Google Account with 2-Step Verification Using 1Password_](https://docs.google.com/document/d/1hL3gYqoV6EWl4bUa2VYLgq0N__CjTvSw4Da2M4x2Hxk/edit#), replace the troubleshoot section with a link to the troubleshooting guide.

**Comment by JessicaLucindaCheng** [comment]
**Progress update**
- Progress: I started a first draft but didn't quite finish it
- Blockers: None yet
- Availability: 6 hours
- ETA: Tue, Feb 11, 2023 to complete first draft

**Tasks**
- [ ] When the guide for this issue is done, in [_Guide: Log into a Google Account with 2-Step Verification Using 1Password_](https://docs.google.com/document/d/1hL3gYqoV6EWl4bUa2VYLgq0N__CjTvSw4Da2M4x2Hxk/edit#), replace the troubleshoot section with a link to the troubleshooting guide.

**Comment by JessicaLucindaCheng** [comment]
**Progress update**
- Progress: I started a first draft but didn't quite finish it
- Blockers: None yet
- Availability: 6 hours
- ETA: Tue, March 14, 2023 to complete first draft

**Tasks**
- [ ] When the guide for this issue is done, in [_Guide: Log into a Google Account with 2-Step Verification Using 1Password_](https://docs.google.com/document/d/1hL3gYqoV6EWl4bUa2VYLgq0N__CjTvSw4Da2M4x2Hxk/edit#), replace the troubleshoot section with a link to the troubleshooting guide.

**Comment by JessicaLucindaCheng** [comment]
**Progress update**
- Progress: I started a first draft but didn't quite finish it
- Blockers: None yet
- Availability: 6 hours
- ETA: Tue, March 14, 2023 to complete first draft

**Tasks**
- [ ] When the guide for this issue is done, in [_Guide: Log into a Google Account with 2-Step Verification Using 1Password_](https://docs.google.com/document/d/1hL3gYqoV6EWl4bUa2VYLgq0N__CjTvSw4Da2M4x2Hxk/edit#), replace the troubleshoot section with a link to the troubleshooting guide.

**Comment by JessicaLucindaCheng** [comment]
**Progress update**
- Progress: I started a first draft but didn't quite finish it
- Blockers: None yet
- Availability: 6 hours
- ETA: April 30, 2023 to complete first draft

**Tasks**
- [ ] When the guide for this issue is done, in [_Guide: Log into a Google Account with 2-Step Verification Using 1Password_](https://docs.google.com/document/d/1hL3gYqoV6EWl4bUa2VYLgq0N__CjTvSw4Da2M4x2Hxk/edit#), replace the troubleshoot section with a link to the troubleshooting guide.

**Comment by JessicaLucindaCheng** [comment]
**Progress update**
- Progress: I started a first draft but didn't quite finish it
- Blockers: None yet
- Availability: 6 hours
- ETA: April 30, 2023 to complete first draft

**Tasks**
- [ ] When the guide for this issue is done, in [_Guide: Log into a Google Account with 2-Step Verification Using 1Password_](https://docs.google.com/document/d/1hL3gYqoV6EWl4bUa2VYLgq0N__CjTvSw4Da2M4x2Hxk/edit#), replace the troubleshoot section with a link to the troubleshooting guide.

**Comment by Aditya23soni** [comment]
<details><summary>Assignee, Labels, Project Board Placement, and Milestones for this issue in the Ops Repo:</summary>
<p>

<img width="329" alt="Screenshot 2024-10-04 at 5 51 07 PM" src="https://github.com/user-attachments/assets/b1193f88-af67-465c-8adf-efe5885e745c">

</p>
</details>

**Comment by Aditya23soni** [comment]
@JessicaLucindaCheng  This guide issue is moving to the knowledgebase-content repo. If you would like to maintain edit access to the issue and its associated files, please fill out the [Google Drive Access Form](https://forms.gle/vnKRqprNYJUG5ET69).

**Comment by Aditya23soni** [comment]
[(https://drive.google.com/drive/folders/12MRORAcPY_-UMHD183PiJFlAdVmOQmIX)]
- Unable to view this document while moving this issue
